hotel_reservation:
    resource: "@HotelBundle/Controller/ReservationController.php"
    type:     annotation

user_client:
    resource: "@UserBundle/Controller/ClientController.php"
    type:     annotation

hotel_chambre:
    resource: "@HotelBundle/Controller/ChambreController.php"
    type:     annotation


user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

hotel:
    resource: "@HotelBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
