<?php

namespace HotelBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUnreservedRoom()
    {
//        $querybuilder = $this->createQueryBuilder()
//            ->select('a')
//            ->from($this->_entityName, 'a')
//            ->where('a')
    }
}
